services:
  mongo:
    image: mongo:latest  
    container_name: qr-code-boost-mongo
    ports:
      - "27017:27017"  
    volumes:
      - mongo-data:/data/db 
  
volumes:
  db_data:
    driver: local
  mongo-data:
    driver: local